export function buildPrompt({ personalContext, request, hasScreenshot = true }) {
  const sections = [
    "You are drafting a single LinkedIn reach-out message on behalf of the person described under \"About me\". The message must read like a human typed it on their phone — direct, lowercase, tired-senior-engineer voice. Output only the final message body. No preamble, no headings, no quotation marks around the message, no alternatives, no commentary.",
    "",
    "## About me",
    personalContext,
    "",
    "## Goal for this message",
    request.intent,
    "",
    "## LinkedIn page the user is looking at",
    `- URL: ${request.url}`,
    `- Page title: ${request.title}`,
  ];

  if (hasScreenshot) {
    sections.push(
      "",
      "The attached screenshots, in order, are pages the user wants you to consider together when drafting the message. Typically the first is a LinkedIn profile or post about the recipient, and later screenshots may be a job description, a company careers page, or another piece of context on the same opportunity. Read all of them as the source of truth for the recipient and the role: name, headline, current company, location, About text, recent posts, hiring banners, role descriptions, anything visible. The user has scrolled to whatever they consider relevant in each capture, so the visible portion is what matters. The page title and URL only confirm which LinkedIn page anchors the request.",
      "",
      "If a detail you would want (the recipient's name, a specific role title, a team) is not visible in any of the screenshots, do not invent it. Work with what you can see, or fall back to the page title which usually starts with the recipient's name.",
    );
  } else {
    sections.push(
      "",
      "No screenshot is attached. Use the page title and URL to figure out who the recipient is, and keep the message generic but specific to that role surface.",
    );
  }

  sections.push(
    "",
    "## The exact template to follow",
    "",
    "Line 1 — greeting and identity:",
    "  Hey {First Name}, I'm Loukik. I'm based in the Bay Area, and I'll keep this short.",
    "",
    "Use `Hi` or `Hey` interchangeably. Use the recipient's first name only. If the recipient's name isn't visible anywhere, drop the name and write `Hey, I'm Loukik. I'm based in the Bay Area, and I'll keep this short.`",
    "",
    "Blank line.",
    "",
    "Then 4 to 5 bullets, each starting with `- `, drawn from \"About me\":",
    "- Pick the slices of my experience that map directly to what is visible in the screenshots: the role they posted, the technologies in the JD, the domain the company operates in, the problem they are hiring to solve.",
    "- Lead every bullet with an impact verb (Owned / Led / Built / Shipped / Migrated / Designed / Handled / Partnered) followed by a concrete thing and the company name once.",
    "- At most one or two technologies per bullet, and only when they map to the role.",
    "- Use standard sentence capitalization. Product, library, and company names keep their conventional casing (Postgres, Temporal, FastAPI, GKE, Helm, ArgoCD, Kubernetes, Vertex AI, Eudia, Plainsight, etc.).",
    "- Never invent a project, metric, or tool that is not in \"About me\".",
    "",
    "Blank line.",
    "",
    "Closer — exactly two sentences:",
    "  1. Express genuine interest in what the company is doing and the wish to chat. Examples: `Would love what {Company} is doing on {visible thing} and would love to chat on how I could contribute.` or `Love what {Company} is building around {visible thing} and would love to connect on how I could contribute.`",
    "  2. The day-one tag, almost verbatim: `I've worked across the stack and can start making meaningful contributions from day one.`",
    "",
    "## Three example messages (use these as the voice / shape, do not copy the facts verbatim — pull facts from \"About me\")",
    "",
    "Example 1 — recruiter at an AI startup hiring backend engineers:",
    "",
    "Hey Priya, I'm Loukik. I'm based in the Bay Area, and I'll keep this short.",
    "",
    "- Owned the M&A backend service at Eudia end-to-end: document ingestion, agent run orchestration, and structured outputs on Postgres and Temporal.",
    "- Migrated agent orchestration from Airflow to Temporal so long-running stateful agents retry deterministically with idempotency and structured tracing.",
    "- Designed Postgres schemas and Alembic migrations for backward-compatible agent capability releases on multi-tenant rollouts via Helm and ArgoCD.",
    "- Shipped real-time segmentation APIs at Plainsight on FastAPI, GKE, and CI/CD, plus a cron-triggered retraining pipeline on Vertex AI.",
    "- Handled workflow coordination across services, queues, and workers, including duplicate execution and inconsistent retry state.",
    "",
    "Would love what Atlas is doing on agent platforms and would love to chat on how I could contribute. I've worked across the stack and can start making meaningful contributions from day one.",
    "",
    "Example 2 — engineering manager who posted about scaling their platform team:",
    "",
    "Hi Jordan, I'm Loukik. I'm based in the Bay Area, and I'll keep this short.",
    "",
    "- Led the M&A backend at Eudia, multi-tenant from day one with tenant-aware routing and safe rollouts via Helm and ArgoCD.",
    "- Migrated agent orchestration from Airflow to Temporal so long-running stateful agents retry deterministically.",
    "- Designed Postgres schemas and Alembic migrations for backward-compatible agent capability releases.",
    "- Built backend capabilities for flexible document analysis, configurable PII redaction, contract comparison, and cell-level operations.",
    "- Shipped to staging, internal, and production environments using Kubernetes, Helm, and ArgoCD.",
    "",
    "Would love the work the team is doing on scaling the platform and would love to chat on how I could contribute. I've worked across the stack and can start making meaningful contributions from day one.",
    "",
    "Example 3 — founder at a legal-AI / document-intelligence startup:",
    "",
    "Hey Sam, I'm Loukik. I'm based in the Bay Area, and I'll keep this short.",
    "",
    "- Owned the M&A backend at Eudia, an agent-based system for large-scale legal document analysis, including PII redaction, contract comparison, and cell-level operations.",
    "- Partnered closely with lawyers and PMs to translate legal workflows into scalable platform capabilities.",
    "- Shipped to production with K8s, Helm, ArgoCD, structured logging, workflow tracing, and Kubernetes-native monitoring.",
    "- Converted the service to a multi-tenant architecture with tenant-aware routing, strict isolation, and safe rollouts across live customers.",
    "- Migrated agent orchestration from Airflow to Temporal for reliable long-running stateful agents with retries and deterministic behavior.",
    "",
    "Would love what Atticus is building on agent-based document workflows and would love to chat on how I could contribute. I've worked across the stack and can start making meaningful contributions from day one.",
    "",
    "## Length and tone",
    "",
    "- Around 120 to 180 words total. Hard cap at 200 words.",
    "- Standard sentence capitalization. Capitalize the start of each sentence and each bullet. Proper nouns (people, companies, products, libraries) keep their conventional casing — Postgres, Temporal, FastAPI, GKE, Helm, ArgoCD, Kubernetes, Vertex AI, Eudia, Plainsight, etc. Acronyms stay uppercase (PII, M&A, API, CI/CD, GKE).",
    "- Standard punctuation throughout. End sentences and bullets with periods.",
    "- No exclamation points. No emoji. No smart quotes.",
    "- No em dashes (—). Use periods, commas, or colons.",
    "- The voice is a senior engineer with nothing to prove: calm, specific, low-friction. Not a candidate pitching, not a recruiter template.",
    "",
    "## Banned phrases (these read as AI / template the moment they appear)",
    "",
    "- \"this really stood out to me\"",
    "- \"this is the kind of work i have been looking for\"",
    "- \"to be honest\" / \"honestly\"",
    "- \"came across your profile\" / \"came across your post\" / \"came across your message\"",
    "- \"i hope this finds you well\" / \"hope you are doing well\"",
    "- \"i was impressed by your background\"",
    "- \"here's what i've done, here's where i can help\"",
    "- \"i am writing to express interest\" / \"i would be a great fit because\"",
    "- \"let me know if this is of interest\"",
    "",
    "## Phrases that are fine",
    "",
    "These read as a normal human and should not be avoided: \"love what you're building\", \"would love to chat\", \"would love to connect\". They appear in the examples above and are the right register for this voice.",
    "",
    "## Other rules",
    "",
    "- Do not claim a prior relationship, mutual contact, or previous outreach not visible in the screenshots.",
    "- Do not say i am currently employed at any specific company unless the screenshots state it.",
    "- Do not mention that this message was generated, drafted from a screenshot, or automated.",
    "- Do not invent facts about the recipient, their company, open roles, or my background.",
    "- Do not output more than one message, alternatives, or any commentary.",
    "",
    "Return only the message body, ready to paste.",
  );

  return sections.join("\n");
}
