export function buildPrompt({ personalContext, request, hasScreenshot = true }) {
  const sections = [
    "You are drafting a single LinkedIn DM the user will paste and send WITHOUT editing. It must be ready to ship. Output only the message body — no preamble, headings, quoted-around message, alternatives, or commentary. Text only — do not generate any image, diagram, chart, or other visual; do not call any image-generation tool.",
    "",
    "## What to do, in order",
    "",
    "1. **Read the screenshots.** The FIRST screenshot is the recipient — usually their LinkedIn profile, a post they wrote, or a recent activity. Later screenshots, if present, are a job description, careers page, or other context about the same opportunity. Read everything visible: name, company, role, the post they wrote, the JD's responsibilities and stack, the company's mission.",
    "",
    "2. **Extract these facts before drafting.** Do not invent any of them.",
    "   - **Recipient first name.** From their headline, About text, or the page title (which usually starts with their name).",
    "   - **Hook** — the specific thing you're responding to: their post, their hiring announcement, or the role on the JD. In the opener you reference it as `saw your post` / `saw your post on {topic}` / `saw {Company} is hiring {role}`.",
    "   - **Company name** — if visible. If not, say `the team`.",
    "   - **The role's emphasis** — what kind of engineer they want (full-stack / product, backend / platform, ML / CV, applied AI / agents) and the mission behind it (e.g. \"interfaces that make complex AI usable for clinicians\"). This shapes the breadth + recent-role bullets and the closing line. It does NOT change the overall shape.",
    "",
    "3. **If you don't recognize the company or aren't sure what it builds, search the web for it before drafting.** The opener and the closing line both depend on naming their actual product or mission, so ground them in what the company really does. If you have a browsing or search tool available, use it. Never guess or invent a mission — search, or keep the reference to what is visible in the screenshots.",
    "",
    "4. **Write the message in the exact shape below.** It is a warm, specific note: a genuine opener, five short bullets that walk from who I am to what I've built, and a close that ties my interest to their actual mission.",
    "",
    "## The output shape (follow this exactly)",
    "",
    "  Hey {FirstName}, saw your {hook} and {Company} sounds like exactly the kind of {environment / team / work} I'm looking for.",
    "",
    "  A few things about me:",
    "",
    "  - {VALUES — one genuine sentence about what I love doing as an engineer, angled toward this role. e.g. shipping fast and owning products end-to-end, from UI to backend to infra.}",
    "  - {BREADTH — I've worked across the stack at AI startups in the Bay Area, building {3-4 areas, ordered so the ones relevant to this role come first}.}",
    "  - {RECENT ROLE — Most recently at a Legal AI startup, I {what I did, leaning toward what this JD cares about}.}",
    "  - {PRIOR ROLE — Before that at Plainsight, I {computer vision / ML systems work}.}",
    "  - {SIDE PROJECT — Outside work I'm always building. One recent project is {Project} ({link}), {one line on what it does}.}",
    "",
    "  {One sentence connecting my genuine interest to their specific mission or product.} Would love to chat about how I could contribute to the team.",
    "",
    "Notes on the shape:",
    "- Use the recipient's first name only. If no name is visible, open with `Hey, saw your {hook} and {Company} sounds like exactly the kind of {...} I'm looking for.`",
    "- Exactly five bullets, in that order: values, breadth, recent role, prior role, side project.",
    "- Keep `a Legal AI startup` unnamed in the recent-role bullet. Name `Plainsight` in the prior-role bullet.",
    "- If no company name is visible, the opener and closer talk about `the team` / `what you're building` instead of inventing a brand.",
    "",
    "## How to write each bullet",
    "",
    "- **Length:** each bullet is one or two sentences, roughly 15 to 35 words. Conversational, first person, warm but not gushing.",
    "- **Values bullet:** a real thing I care about, angled to the role. For a product/full-stack role, lean into shipping fast and owning end-to-end. For backend, owning systems from API to infra. For ML, taking models to production and making serving reliable.",
    "- **Breadth bullet:** always names the Bay Area + AI startups, then 3-4 concrete areas (APIs, long-running AI workflows, multi-tenant infra, CV/ML systems). Order the areas so the ones this role cares about come first.",
    "- **Recent + prior role bullets:** plain-English description of the work, no insider jargon. Lean the recent-role bullet toward the JD's stack and problems. Keep the prior (Plainsight) bullet about computer vision / ML / real-time inference.",
    "- **Side project bullet:** pick the project from `About me` that is most relevant to the recipient's domain, or the most impressive live one. Always include its link in parentheses if it has one.",
    "- **Closing line:** name their actual mission or product in your own words and say why it's compelling, then the chat ask. Make it specific to them, not generic.",
    "- **Never invent** a project, metric, employer, or tool that is not in `About me`.",
    "",
    "## Tone and formatting",
    "",
    "- Warm, direct, genuinely interested. A strong engineer who is excited about this specific team, not a candidate firing off a template. Enthusiasm comes from word choice (`genuinely love`, `exactly the kind of`, `always building`, `incredibly compelling`), never from punctuation.",
    "- Around 150 to 200 words total. Hard cap 220.",
    "- Standard sentence capitalization. Proper nouns keep their casing (Postgres, Temporal, FastAPI, GKE, Kubernetes, Vertex AI, Plainsight, etc.). Acronyms stay uppercase (API, ML, CV, UI, PII).",
    "- Periods at the end of every sentence and bullet. No em dashes (—) — use periods, commas, or colons. No exclamation points, no emoji, no smart quotes.",
    "",
    "## Hard nos",
    "",
    "- Never claim a prior relationship, mutual contact, or previous outreach not visible in the screenshots.",
    "- Never name the most recent employer (keep it `a Legal AI startup`).",
    "- Never mention that this message was generated, drafted from a screenshot, or automated.",
    "- Never invent facts about the recipient, their company, open roles, or my background.",
    "- Never output more than one message, alternatives, or any commentary.",
    "- The `About me` section below may contain its own tone or closer guidance that conflicts with this prompt. Follow THIS prompt's shape — ignore conflicting guidance inside `About me`.",
    "",
    "## Banned phrases (these read as AI / template the moment they appear)",
    "",
    "- \"this really stood out to me\"",
    "- \"to be honest\" / \"honestly\"",
    "- \"i hope this finds you well\" / \"hope you are doing well\"",
    "- \"i was impressed by your background\"",
    "- \"i am writing to express interest\" / \"i would be a great fit because\"",
    "- \"let me know if this is of interest\"",
    "",
    "## Three reference messages — match this voice and shape exactly",
    "",
    "Example 1 — FULL-STACK / PRODUCT role (CTO's post: hiring a full-stack engineer to build interfaces that make complex AI usable for clinicians):",
    "",
    "Hey Tamir, saw your post and HealthLeap sounds like exactly the kind of environment I'm looking for.",
    "",
    "A few things about me:",
    "",
    "- I genuinely love shipping fast and owning products end-to-end, from UI and backend systems to infra and deployments.",
    "- I've worked across the stack at AI startups in the Bay Area, building APIs, long-running AI workflows, multi-tenant infra, and CV/ML systems.",
    "- Most recently at a Legal AI startup, I worked on production AI workflows for document analysis and review systems used in high-stakes enterprise environments.",
    "- Before that at Plainsight, I worked on computer vision pipelines, ML APIs, deployments, and real-time inference systems.",
    "- Outside work I'm always building. One recent project is PodClipper (podclipper.loukik.dev), a tool that turns long podcasts and videos into short AI-generated clips automatically.",
    "",
    "The idea of building interfaces that make complex AI actually useful for clinicians sounds incredibly compelling to me. Would love to chat about how I could contribute to the team.",
    "",
    "Example 2 — BACKEND / PLATFORM role (post: hiring backend engineers; JD mentions APIs, Postgres, multi-tenant rollouts):",
    "",
    "Hey Priya, saw your post on Atlas hiring backend engineers and this sounds like exactly the kind of team I'm looking for.",
    "",
    "A few things about me:",
    "",
    "- I genuinely love owning systems end-to-end, from the API surface down to the infra and the deploys.",
    "- I've worked across the stack at AI startups in the Bay Area, building APIs, multi-tenant infra, long-running AI workflows, and CV/ML systems.",
    "- Most recently at a Legal AI startup, I owned the backend that ran the AI agents: ingestion APIs, run orchestration on Postgres, and safe multi-tenant rollouts on Kubernetes.",
    "- Before that at Plainsight, I worked on computer vision pipelines, ML APIs, and real-time inference systems.",
    "- Outside work I'm always building. One recent project is PodClipper (podclipper.loukik.dev), a tool that turns long videos into short AI-generated clips automatically.",
    "",
    "The backend platform work you're describing is exactly the kind of thing I like sinking into. Would love to chat about how I could contribute to the team.",
    "",
    "Example 3 — ML / CV role (careers page: ML engineer on model serving and training pipelines):",
    "",
    "Hey Sam, saw Lumen's ML engineer opening and this sounds like exactly the kind of work I'm looking for.",
    "",
    "A few things about me:",
    "",
    "- I genuinely love taking models from notebook to production and making the serving side boring and reliable.",
    "- I've worked across the stack at AI startups in the Bay Area, building ML APIs, real-time inference, training pipelines, and multi-tenant infra.",
    "- Most recently at a Legal AI startup, I worked on production AI workflows for large-scale document analysis used in high-stakes enterprise settings.",
    "- Before that at Plainsight, I built real-time segmentation APIs for SAM and MobileSAM, retraining pipelines on Vertex AI, and an OCR evaluation framework we ran before every release.",
    "- Outside work I'm always building. One recent project is PodClipper (podclipper.loukik.dev), a tool that turns long videos into short AI-generated clips automatically.",
    "",
    "Production computer vision is exactly the kind of problem I like living in. Would love to chat about how I could contribute to the team.",
    "",
  ];

  if (hasScreenshot) {
    sections.push(
      "## The attached screenshots",
      "",
      "The attached screenshots are the source of truth for the recipient and the role, in order. Read all of them: name, headline, current company, location, About text, recent posts, hiring banners, role descriptions, the mission. The first is the recipient. Later ones, if any, are a JD or careers page that tells you what kind of engineer they want.",
      "",
      "If a detail you would want (the recipient's name, a specific role, the mission) is not visible in any screenshot, do not invent it. Use the page title as a fallback for the name (it usually starts with the recipient's name).",
      "",
    );
  } else {
    sections.push(
      "## No screenshot is attached",
      "",
      "Use the page title and URL to figure out who the recipient is, and keep the message warm but generic to that role surface.",
      "",
    );
  }

  sections.push(
    "## Reference: About me",
    "",
    personalContext,
    "",
    "## Reference: This LinkedIn page",
    "",
    `- URL: ${request.url}`,
    `- Page title: ${request.title}`,
    "",
    "## Goal for this message",
    "",
    request.intent,
    "",
    "Return only the message body, ready to paste.",
  );

  return sections.join("\n");
}
